[package]
name = "libjfmt"
version = "0.1.0"
edition = "2024"

[dependencies]
tree-sitter = "0.22"
tree-sitter-java = "0.21"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
